<a href="https://colab.research.google.com/github/KlymT/Py_R_for_DS-/blob/master/PR4DS_Module_2_Python_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Модуль 2. Основи мови програмування Python

# Python як мова програмування

Python - це мова програмування, яка:
- інтерпретована: команди виконуються одна за одною, необхідності компіляції немає;
- високорівнева: синтаксис дуже подібний до природньої мови, код виглядає як псевдокод, не зав'язана до апаратної частини (хоча можуть бути проблеми при використанні сторонніх модулів та бібліотек під різні ОС);
- загального призначення: може застосовуватися для розробки програмного забезпечення в різних предметних областях та вирішення різних завдань;

Підтримує наступні парадигми:
- структурне програмування;
- функціональне програмування;
- об'єктно-орієнтоване програмування.

Офіційний tutorial можна знайти за посиланням: https://docs.python.org/3.6/tutorial/index.html

## Запуск коду

*Основні варіанти запуску коду:*
1. через інтерпретатор Python, для чого в терміналі (консоль) інтерпретатор запускається командою `python`; більше підходить для швидкого протипіювання чи виконання нескладних операцій;

```shell
$ python
'Python 3.4.4 (v3.4.4:737efcadf5a6, Dec 20 2015, 20:20:57) [MSC v.1600 64 bit (AMD64)] on win32'
'Type "help", "copyright", "credits" or "license" for more information.'
>>> 2 + 2 == 5
False
>>>
```

2. через IDE, наприклад, PyCharm; ідеально підходить для відлагодження (debugging) програм, розробки повторно-використовуваних модулів та пакетів;

3. через виконання скрипта; даний варіант підходить для перевірки роботи нескладних, примітивних та невеликих за розміром програм;

```shell
$ python path/to/my/module.py args
'result will be displayed here'
```

4. використовуючи Jupyter Notebook чи аналог, де потрібна інтерактивність і відображення результатів "on-fly", включаючи тексти опису, графіки і т.д.

## Python PEP8

PEP8 (<a href="https://www.python.org/dev/peps/pep-0008/" target="_blank">Style Guide for Python Code</a>) - convention щодо стилізації коду на Python.

![](https://www.iphones.ru/wp-content/uploads/2019/02/13-inch-macbook-pro-1240x630.jpg)

[тут картинка](https://www.iphones.ru/wp-content/uploads/2019/02/13-inch-macbook-pro-1240x630.jpg)

$$
x = y \times 2
$$

Нижче приклад The Zen of Python або аналог 10 заповідей :-)

In [ ]:
import this

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!


## Синтаксис мови

Основні, ключові моменти, які потрібно запам'ятати з PEP8:

* Блоки виділяються відступами, 4 пробіли (рекомендовано) або табуляція (не рекомендується використовувати).
* Коментарі виділяються символом `#`.
* Опис функцій, методів, модулів - DocStrings в блоці з потрійними одинарними `'''text goes here'''` або подвійними лапками `"""text goes here"""`.
* Завершення рядка коду - завершення команди.
* Пробіли в межах одного рядка не мають значення.
* Кодування файлів `UTF-8`.

Нижче приведено приклад оформлення коду.

In [ ]:
a,                b                           = 1,                                                             2
a

1

In [ ]:
temp = [1, 2, 3, 4]

temp

[1, 2, 3, 4]

In [ ]:
list()

[]

In [ ]:
#a, b = 1, 2

"""
Приклад DocStrings
srfkl
sdf
sfd
sf
dfgs
gd
2+2
"""
# Приклад коментаря
temp = [1, 2, 3, 4]

result = list()

for val in temp:
    if val % 2 == 0: # ще один приклад коментаря та виділення блока відступами
        result.append(str   (val   ))  # пробіли в межах одного рядка не враховуються, але так краще не писати

#r-style
#for (val in temp){
#    if (val % 2 == 0){
#        result.append(str   (val   ))
#    }
#}
        
print('Result "list": ' + ', '.join(result))

for val in result:
    tmp = int(val)
    print("x={}, x^2={}".  # приклад перенесення рядка
          format(val, str(tmp * tmp)))

Result "list": 2, 4
x=2, x^2=4
x=4, x^2=16


# Семантика мови
## Змінні та об'єкти

* Все, що в Python - це об'єкти.
* Об'єкти двох типів - mutable, immutable.
* Змінні - це вказівники (pointers).

Mutable об'єкти - це ті, які можна змінювати. Тому в ході розробки потрібно бути дуже обережним при роботі зі списками, словниками та іншими об'єктами при їх присвоєні новим змінним, при передачі як аргументів методів. В основному, щоб уникнути ситуації "випадкової" зміни об'єкту, що може призвести до порушення алгоритму роботи.

Три нижче приведені вбудовані функції можна використовувати для:
- `type(obj)` - для отримання типу об'єкту (див. https://docs.python.org/3.6/library/functions.html#type)
- `issubclass(obj_class, class)` - для перевірки, що клас об'єкту є підкласом або класом потрібного типу (див. https://docs.python.org/3.6/library/functions.html#issubclass)
- `isinstance(obj, class)` - для перевірки типу об'єкту (див. https://docs.python.org/3.6/library/functions.html#isinstance)

Якщо буде цікаво, то можно почитати в офіційній документації про Data model: https://docs.python.org/3.6/reference/datamodel.html#the-standard-type-hierarchy

In [ ]:
# Приклад перевірки типу
x = 10.0
print(x.is_integer())
print('Type of x is <{}>'.format(type(x).__name__), "yy")
print('x {} subclass of <int>'.format('IS' if issubclass(type(x), int) else 'IS NOT'))
print('x {} instance of <str>'.format('IS' if isinstance(x, str) else 'IS NOT'))

True
Type of x is <float> yy
x IS NOT subclass of <int>
x IS NOT instance of <str>


In [ ]:
# Приклад роботи з immutable об'єктами
x = 10
y = x

y = 11

print('Before:\tx={}, y={}'.format(x, y))

Before:	x=10, y=11


In [ ]:
# Після збільшення Х на 10, значення Y залишається не змінним
x += 10 # x = x + 10
x = x + 10
print('After:\tx={}, y={}'.format(x, y))

After:	x=30, y=11


In [ ]:
# Приклад роботи з mutable об'єктами
x = [1, 2, 3, 4]  # Оголошення списку з 4 елементів; list - mutable type
y = [1, 0, 1, 0]
print('Before:\tx={}, y={}'.format(x, y))

Before:	x=[1, 2, 3, 4], y=[1, 0, 1, 0]


In [ ]:
len(x)+len(y), "text 1" + "text 2"

(8, 'text 1text 2')

In [ ]:
z = []

for i in range(len(x)):
  z.append(x[i] + y[i])

z

[2, 2, 4, 4]

In [ ]:
9 / 0

ZeroDivisionError: ignored

In [ ]:
import numpy as np

np.concatenate([np.array(x), np.array([9, 2, 88, 0], dtype='float')])

array([ 1.,  2.,  3.,  4.,  9.,  2., 88.,  0.])

In [ ]:
z[0:3] = 8, 8, 8

z

[8, 8, 8, 4]

In [ ]:
# Значення останнього елементу списку Y встановлено в 0
# Зміна застосовується до X та Y
y[1:3] = 0,2,0  # Встановлення значення останнього елементу в 0
print('After:\tx={}, y={}'.format(x, y))

After:	x=[1, 2, 3, 4], y=[1, 0, 2, 0, 0]


In [ ]:
[-9999,  0.00000000, 1, 2, 3, 4, True, False, 1.999999999999999]

[-9999, 0.0, 1, 2, 3, 4, True, False, 1.999999999999999]

In [ ]:
import numpy as np

x = np.array([-9999,  0.00000000, 1, 2, 3, 4, True, False, 1.99999999999999], dtype='int') #, dtype = np.float
#np.inf, -np.inf,np.nan, "some text", "",
x

array([-9999,     0,     1,     2,     3,     4,     1,     0,     1])

In [ ]:
x = np.array([0, -1, 1, 2.0, True, '', '5', [2], None, np.inf, np.nan], dtype = np.bool8)

y = np.array([True, False, True, False, True, False], dtype = np.int8)

x

array([False,  True,  True,  True,  True, False,  True,  True, False,
        True,  True])

In [ ]:
x = np.array([3,4,6,5,1,2,7])
y = np.array([1,2,3,4,5,6,0])

In [ ]:
print(x.shape)
print(y.shape)

x / y

(7,)
(7,)


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:4: RuntimeWarning: divide by zero encountered in true_divide
  after removing the cwd from sys.path.


array([3.        , 2.        , 2.        , 1.25      , 0.2       ,
       0.33333333,        inf])

In [ ]:
# Приклад роботи з mutable об'єктами через модуль copy.deepcopy
import copy

from math import pi

#pi = 3

x = [1, 2, 3, 4, pi]

y = copy.copy(x)

print('Before:\tx={}, y={}'.format(x, y))

# Значення останнього елементу списку Y встановлено в 0.
# Зміна застосовується до Y
x[-1] = 0
print('After:\tx={}, y={}'.format(x, y))

Before:	x=[1, 2, 3, 4, 3.141592653589793], y=[1, 2, 3, 4, 3.141592653589793]
After:	x=[1, 2, 3, 4, 0], y=[1, 2, 3, 4, 3.141592653589793]


In [ ]:
??deepcopy

# Вбудовані типи даних

Основні типи даних
* int
* float
* complex
* bool
* str
* NoneType

Python динамічно типізована мова програмування, тому в ній не потрібно оголошувати зміні з вказанням типу, як, наприклад, в C++, Java.

Офіційна документація по Buit-in Types - https://docs.python.org/3.6/library/stdtypes.html

In [ ]:
x = [1,23,4]
x[-1]

4

In [ ]:
# Приклад динамічної типізації
test = 10  # Оголошення змінної типу <int>
print('was %d integer ' % test)
print('was {} integer '.format(test))
print(f'was {test} integer ')
print('was ' + str(test) + ' integer ')
print('was integer ' + str(test))
test = "test"  # Присвоєння змінній нового значення типу <str>
print('became string %s' % test)

was 10 integer 
was 10 integer 
was 10 integer 
was 10 integer 
was integer 10
became string test


## Тип int

Використовується для представлення цілих чисел.

In [ ]:
# Приклад роботи з int
x = 10
y = 3
z = x * y
print("z=x*y, z=%d" % z)

z = x / y
print("z=x*y, z=%f" % z)

# Даний варіант ділення було додано в Python 3 для підтримки ділення цілих чисел
# як в Python 2, де при ділені двох цілих чисел в результаті - ціле число, а дробова частина відкидається
z = x ** y #2^3
print("z=x*y, z=%f" % z)

z=x*y, z=30
z=x*y, z=3.333333
z=x*y, z=1000.000000


In [ ]:
x % y #залишок

1

In [ ]:
int(x / y) == (x // y)

True

## Тип float
Використовується для представлення чисел з плаваючою крапкою.

Нижче приклад роботи з типом float, який демонструє одну з проблем при використанні даного типу при порівнянні значень.

Причина - особливості збереження та представлення чисел з плаваючою крапкою. Тому, для уникнення проблем рекомендується використовувати клас Decimal (https://docs.python.org/3.6/library/decimal.html#decimal-objects).

In [ ]:
# Приклад роботи з float
x = 10.6
y = True + 2.51 + 1

print('Values as they were defined')
print('x = {}'.format(x))
print('y = {}'.format(y))

print('Values as they stored in memory')
print('x = {0:.4f}'.format(x))
print('y = {0:.100f}'.format(y))

Values as they were defined
x = 10.6
y = 4.51
Values as they stored in memory
x = 10.6000
y = 4.5099999999999997868371792719699442386627197265625000000000000000000000000000000000000000000000000000


In [ ]:
# Приклад проблеми, яка виникає при порівнянні значень типу <float>
a = 0.1
b = 0.2
c = 0.3

is_equal = (a + b) == c
print('a + b {} c\n'.format('==' if is_equal else '!='))

print('Values as they stored in memory')
print('\ta = {0:.17f}'.format(a))
print('\tb = {0:.17f}'.format(b))
print('\tc = {0:.17f}'.format(c))

a + b != c

Values as they stored in memory
	a = 0.10000000000000001
	b = 0.20000000000000001
	c = 0.29999999999999999


In [ ]:
# Приклад роботи з Decimal
from decimal import *

context = getcontext()
print(context, end='\n')

x_d = Decimal(str(x))
y_d = Decimal(str(y))

print('prec: {}'.format(context.prec))
print('x = {0:.17f}'.format(x_d))
print('y = {0:.17f}'.format(y_d))
print()

original_prec = context.prec
context.prec = 2
print('prec: {}'.format(context.prec))
print('x = {}'.format(x_d))
print('y = {}'.format(y_d))
print()

context.prec = original_prec
# Приклад використання вбудованих функцій класу Decimal
x_d = Decimal('100')
z_d = x_d.sqrt()
print('prec: {val}'.format(val=context.prec))
print('sqrt(x_d) = {}'.format(z_d))

z_d = x_d.log10()
print('log(x_d) = {}'.format(z_d))
print(z_d)

Context(prec=28, rounding=ROUND_HALF_EVEN, Emin=-999999, Emax=999999, capitals=1, clamp=0, flags=[], traps=[InvalidOperation, DivisionByZero, Overflow])
prec: 28
x = 10.60000000000000000
y = 4.51000000000000000

prec: 2
x = 10.6
y = 4.51

prec: 28
sqrt(x_d) = 10
log(x_d) = 2
2


In [ ]:
Decimal('0.1') + Decimal('0.2') #== Decimal('0.3')

Decimal('0.3')

In [ ]:
float(Decimal('0.1') + True)

1.1

In [ ]:
z = np.array([0.1]) + np.array([0.2])

print(z, np.array([0.3]))

[0.3] [0.3]


In [ ]:
(np.array([11.1 + True, 1, -1], dtype = np.float)/0) + \
(np.array([11.1 + True, 1, 1], dtype = np.float)/0)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in add
  """Entry point for launching an IPython kernel.


array([inf, inf, nan])

## Тип str

Тип, який використовується для представлення рядків.

Python надає багато можливостей для роботи з даним типом, тому за це його і люблять :-)

Що важливо запам'ятати:
- Цей тип immutable, тобто його не можна модифікувати, наприклад, по індексу.
- Рядки оголошуються в одинарних `'text'` чи подвійних `"text"` лапках, або потрійних одинарних `'''text'''` чи подвійних `"""text"""` лапках.
- Python містить гнучкий механізм для форматування рядків.
- В Python3 всі рядки представленні в вигляді послідовності `unicode` символів.
- Для отримання довжини використовується вбудована функція `len(str_obj)`.

Офіційна документація:
- https://docs.python.org/3.6/library/stdtypes.html#text-sequence-type-str
- https://docs.python.org/3.6/library/string.html
- https://docs.python.org/3.6/library/string.html#format-examples - приклади форматування
- https://docs.python.org/3.6/library/stdtypes.html#string-methods - стандартні методи str

In [ ]:
# Приклад роботи з str
s1 = 'This is \'test\' string#1\n'
s2 = "This is \"test\" string#2\t"
s3 = """
This 'is' "test" string #3\r
"""

print("s1 = " + s1)
print("s2 = %s" % s2)
print("s3 = {}".format(s3))
print('length = {var}\n'.format(var=len(s1)))
print(f"s3 = {s3}")
print(f"value = {x}")
print("value = " + str(x))

s1 = This is 'test' string#1

s2 = This is "test" string#2	
s3 = 
This 'is' "test" string #3

length = 24

s3 = 
This 'is' "test" string #3

value = 10.6
value = 10.6


In [ ]:
[i+"Слава Україні!" for i in s1]

['TСлава Україні!',
 'hСлава Україні!',
 'iСлава Україні!',
 'sСлава Україні!',
 ' Слава Україні!',
 'iСлава Україні!',
 'sСлава Україні!',
 ' Слава Україні!',
 "'Слава Україні!",
 'tСлава Україні!',
 'eСлава Україні!',
 'sСлава Україні!',
 'tСлава Україні!',
 "'Слава Україні!",
 ' Слава Україні!',
 'sСлава Україні!',
 'tСлава Україні!',
 'rСлава Україні!',
 'iСлава Україні!',
 'nСлава Україні!',
 'gСлава Україні!',
 '#Слава Україні!',
 '1Слава Україні!',
 '\nСлава Україні!']

In [ ]:
# str slicing
tmp = s1[:]
print('Original:\t' + s1)
print('Result:\t\t' + tmp)

Original:	This is 'test' string#1

Result:		This is 'test' string#1



In [ ]:
# Приведення str верхнього регістру
s1.upper(), s1.lower()

("THIS IS 'TEST' STRING#1\n", "this is 'test' string#1\n")

In [ ]:
list(s1)

['T',
 'h',
 'i',
 's',
 ' ',
 'i',
 's',
 ' ',
 "'",
 't',
 'e',
 's',
 't',
 "'",
 ' ',
 's',
 't',
 'r',
 'i',
 'n',
 'g',
 '#',
 '1',
 '\n']

In [ ]:
# Приведення str до списку символів
tmp = list(s1)
np.array(tmp, dtype = 'str')

array(['T', 'h', 'i', 's', ' ', 'i', 's', ' ', "'", 't', 'e', 's', 't',
       "'", ' ', 's', 't', 'r', 'i', 'n', 'g', '#', '1', '\n'],
      dtype='<U1')

In [ ]:
# Розділення str по роздільнику (по замовчуванням - пробіл)
tmp = list(s1.split())
print(tmp)

tmp = list(s1.split('i'))
print(tmp)

['This', 'is', "'test'", 'string#1']
['Th', 's ', "s 'test' str", 'ng#1\n']


In [ ]:
s1.replace("i", "A")

"ThAs As 'test' strAng#1\n"

In [ ]:
# Трошки магії
res = "True " + 'yyer'
res

'True yyer'

## Тип bool

Примітивний тип, який може мати два можливих значення: True та False.

Будь-який інший тип може бути приведений до типу `bool` з використанням конструктора `bool()`:
- будь-яке число, яке рівне 0 - False, інакше - True;
- None - завжди False;
- пустий рядок - False, інакше - True;
- для структурних типів (set, dict і т.д.) порожня послідовність - False, інакше - True.

In [ ]:
# Приклади роботи з типом bool
b1 = True
b2 = False
b3 = bool("")
b4 = bool("abc")
b5 = bool(-2.2)
b6 = bool(0.0)
b7 = bool(-10)
b8 = bool(np.array([]))
b9 = bool(" ")
b10 = bool({})
b11 = bool(None)
b12 = bool(np.nan)

# ==  is
# != is not ~
# <
# >
# >=
# <=

print('b1 is ' + str(b1))
print('b2 is ' + str(b2))
print('b3 is ' + str(b3))
print('b4 is ' + str(b4))
print('b5 is ' + str(b5))
print('b6 is ' + str(b6))
print('b7 is ' + str(b7))
print('b8 is ' + str(b8))
print('b9 is ' + str(b9))
print('b10 is ' + str(b10))
print('b11 is ' + str(b11))
print('b12 is ' + str(b12))

b1 is True
b2 is False
b3 is False
b4 is True
b5 is True
b6 is False
b7 is True
b8 is False
b9 is True
b10 is False
b11 is False
b12 is True


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:9: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if __name__ == '__main__':


# Структури даних

Основні, найчастіше вживані структури даних:
* list
* set
* tuple
* dict

## list


Вбудована структура даних, яка є впорядкованою (елементи зберігаються в порядку додання) та mutable.

Що важливо запам'ятати:
- елементи в списку можуть бути різного типу;
- індексація розпочинається з 0;
- зручні операції slicing по конструкції `list[a:b:c]`;
- є можливість доступу до елементів по від'ємного індексу - з кінця списку.

Містить ряд вбудованих методів для роботи, по частині яких нижче приведені приклади.

Офіційна документація по вбудованим методам - https://docs.python.org/3/tutorial/datastructures.html#more-on-lists

In [ ]:
# Оголошенния списку
l1 = [1, 2, '3', 'text', Decimal('20'), False, None, [1, 3, [32, 4]]]  # Елементи різного типу
l2 = []  # Порожній список
l3 = list()  # З використанням конструтора типу <list>

print("l1: \t{}".format(l1))
print("l2: \t{}".format(l2))
print("l3: \t{}".format(l3))

l1: 	[1, 2, '3', 'text', Decimal('20'), False, None, [1, 3, [32, 4]]]
l2: 	[]
l3: 	[]


In [ ]:
np.array(l1, dtype = np.object)

array([1, 2, '3', 'text', Decimal('20'), False, None,
       list([1, 3, [32, 4]])], dtype=object)

In [ ]:
# Приклади slicing
print('First 5: ' + str(l1[:5]))
print('From 2 to end: ' + str(l1[2:]))
print(l1[:2:-3])

First 5: [1, 2, '3', 'text', Decimal('20')]
From 2 to end: ['3', 'text', Decimal('20'), False, None, [1, 3, [32, 4]]]
[[1, 3, [32, 4]], Decimal('20')]


In [ ]:
# Приклади роботи по індексу
print('First: ' + str(l1[0]))
print('Last: ' + str(l1[-1]))

First: 1
Last: [1, 3, [32, 4]]


In [ ]:
# Приклади отримання довжини
print('Length: ' + str(len(l1)))

Length: 8


In [ ]:
#print(temp[0])
#np.array([temp])[0][0]

In [ ]:
# Приклади вибірки 0 елементу з використанням pop
temp = l1.pop()
print('First removed: ' + str(l1))
print(temp)

First removed: [1, 2, '3', 'text', Decimal('20'), False, None]
[1, 3, [32, 4]]


In [ ]:
x

10.6

In [ ]:
# Приклади додання елементу до списку
l1.append(['NEW', 4])
print('Added new element: ' + str(x))
l1

Added new element: 10.6


[1, 2, '3', 'text', Decimal('20'), False, None, ['NEW', 4]]

In [ ]:
# Приклади розширення одного списку іншим
l1.extend(['e1', 'e2', 'e3'])
print('Extended: ' + str(l1))

Extended: [1, 2, '3', 'text', Decimal('20'), False, None, ['NEW', 4], 'e1', 'e2', 'e3']


In [ ]:
# Приклади додання двох списків
test = l1 + ['e1', 'e2', 'e3']
print(test)

f = ["terr",'e1', 'e2', 'e3']
f.sort()
print(f)

[1, 2, '3', 'text', Decimal('20'), False, None, ['NEW', 4], 'e1', 'e2', 'e3', 'e1', 'e2', 'e3']
['e1', 'e2', 'e3', 'terr']


In [ ]:
# Приклади сортування списків
unsorted_list = [3, 65, 4, -2, -100, 0]
print('Un-Sorted: ' + str(unsorted_list))

unsorted_list.sort(reverse=True)
print('Sorted: ' + str(unsorted_list))

char_list = ['a', 'b', 'c', 'aa', 1 , '1', False]
char_list[0] = 1#'Nothing'
print(char_list)

Un-Sorted: [3, 65, 4, -2, -100, 0]
Sorted: [65, 4, 3, 0, -2, -100]
[1, 'b', 'c', 'aa', 1, '1', False]


In [ ]:
f = np.array(char_list, dtype = np.bool)
f = np.array(f, dtype=np.float)
f[f == 0] = 7.99
f.sort()
f

array([1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 7.99])

## tuple

Структура даних, яка дуже схожа до списків, але з поправкою на те, що tuple - immutable, що означає, що після його створення модифікувати його вже не можливо, наприклад, по індексу.

Зачасту використовується для:
- передачі параметрів в методи через `*args`;
- поверення декількох значень після виконання методу;
- при роботі з CSV файлами.

Офіційна документація - https://docs.python.org/3.6/library/stdtypes.html#tuple.

In [ ]:
t1 = (1, 2, 3)

t1 = 1,2,3

a, b, c = 1, 2, 3

In [ ]:
(3,)

(3,)

In [ ]:
# Приклад оголошення tuple

t2 = tuple()
t3 = ()
t4 = 4, 5, 6, (7, 9, (4, 3))
t5 = (1,)

print('t1 type is: ' + str(type(t1)))
print('t1: ' + str(t1))
print('t2: ' + str(t2))
print('t3: ' + str(t3))
print('t4: ' + str(t4))
print('t5: ' + str(type(t5)))

t1 type is: <class 'tuple'>
t1: (1, 2, 3)
t2: ()
t3: ()
t4: (4, 5, 6, (7, 9, (4, 3)))
t5: <class 'int'>


In [ ]:
train_x, _, _, test_y = 1, 2, 3, 4
_+2

5

In [ ]:
train_x = 1, 2, 3, 4
train_x * 2

(1, 2, 3, 4, 1, 2, 3, 4)

In [ ]:
train_x

(1, 2, 3, 4)

In [ ]:
# Приклад створення нового tuple шляхом додання двух окремих
tmp = (3, 4, 5, 6, 9)
res = t1 + tmp
print('Result: ' + str(res))
print('Length: ' + str(len(res)))

Result: (1, 2, 3, 3, 4, 5, 6, 9)
Length: 8


In [ ]:
a, _, b, _, _ = tmp

In [ ]:
# Приклад "розпакування" tuple в окремі змінні
#a, b, *_ = tmp  # _ використовується для ігнорування "не потрібних" значень
"a={}, b={}".format(a, b)

'a=3, b=5'

In [ ]:
x = 0.5
print(x.as_integer_ratio())
numerator, denominator = x.as_integer_ratio()
print('num = ' + str(numerator))
print('den = {}'.format(denominator))
print('num / den = ' + str(numerator / denominator))

(1, 2)
num = 1
den = 2
num / den = 0.5


In [ ]:
# Демострація immutable
try:
    t1[0] = None
except Exception as e:
    print("Error on tuple modification: "+ str(e))

tuple(sorted(tmp, reverse=True))

Error on tuple modification: 'tuple' object does not support item assignment


(9, 6, 5, 4, 3)

## dict

Структура даних, яка дозволяє зберігати дані в вигляді "ключ-значення".

Важливо знати, що:
- елементи словника зберігаються в невпорядкованому вигляді, тобто порядок додання елементів не зберігається (для цих цілей потрібно використовувати OrderedDict);
- ключем може бути лише об'єкт, який immutable, тобто по ньому можна вирахувати hash, наприклад, list не може бути ключем.

Офіційна документація - https://docs.python.org/3.6/library/stdtypes.html#mapping-types-dict

In [ ]:
# Приклади оголошення dict
d1 = {}
d2 = dict()
d3 = dict((('a', 1), ('b', 2)))
d4 = {
    'a': [1,3,4,5], 
    'b': (2,3), 
    4: {5:{7:8}}, 
    None: 10,
    (1,3): 7,
    7.8: [],
    True: (((5,())), 5)
}

print('d1 = ' + str(type(d1)))
print('d2 = ' + str(type(d2)))
print('d3 = ' + str(d3))
print('d4 = ' + str(d4))

d1 = <class 'dict'>
d2 = <class 'dict'>
d3 = {'a': 1, 'b': 2}
d4 = {'a': [1, 3, 4, 5], 'b': (2, 3), 4: {5: {7: 8}}, None: 10, (1, 3): 7, 7.8: [], True: ((5, ()), 5)}


In [ ]:
data = {
    'height': [184, 178, 167, 161, 188, 170],
    'weight': [82, 71, 59, 61, 89, 77]
}

data

{'height': [184, 178, 167, 161, 188, 170], 'weight': [82, 71, 59, 61, 89, 77]}

In [ ]:
import pandas as pd

df = pd.DataFrame(data)

df.index = ['Roman', 'Sergiy', "Sasha", "Inna", "Alex", "Vada"]

df

df['weight_height_index'] = df['height'] / df['weight']

df

height  weight  weight_height_index
Roman      184      82             2.243902
Sergiy     178      71             2.507042
Sasha      167      59             2.830508
Inna       161      61             2.639344
Alex       188      89             2.112360
Vada       170      77             2.207792

In [ ]:
pd.DataFrame({
    'x': 1,
    'y': [1,2,3,4,5]
})

x  y
0  1  1
1  1  2
2  1  3
3  1  4
4  1  5

In [ ]:
df = pd.DataFrame({
    'age': 20,
    'type': 'yry',
    (87, 89): [True, False, True]
})

df

#np.sum(df['age'])

age type  (87, 89)
0   20  yry      True
1   20  yry     False
2   20  yry      True

In [ ]:
# Приклад оголошення з використанням zip
l1 = [1, 2, 4,6]
l2 = [3, 4, 5,7]
l3 = [6, 7, 8, 9]
print(list(zip(l1, l2)))
test = dict(zip(l1, l2))

print(test)

print(list(zip(l1, l2, l3)))

[(1, 3), (2, 4), (4, 5), (6, 7)]
{1: 3, 2: 4, 4: 5, 6: 7}
[(1, 3, 6), (2, 4, 7), (4, 5, 8), (6, 7, 9)]


In [ ]:
np.array(list(zip(l1, l2, l3)))

array([[1, 3, 6],
       [2, 4, 7],
       [4, 5, 8],
       [6, 7, 9]])

In [ ]:
np.correlate(np.array(list(zip(l1, l2, l3)))[:,1], 
             np.array(list(zip(l1, l2, l3)))[:,2])

array([149])

In [ ]:
f = np.array(list(zip(l1, l2, l3)))
f, f[:, [0,2]]

(array([[1, 3, 6],
        [2, 4, 7],
        [4, 5, 8],
        [6, 7, 9]]), array([[1, 6],
        [2, 7],
        [4, 8],
        [6, 9]]))

In [ ]:
# Приклад присвоєння нового значення по ключу
d1['key'] = 'val'
d1

{'key': 'val'}

In [ ]:
list(d1.values()), d1.keys()

(['val'], dict_keys(['key']))

In [ ]:
# Приклад вибірки елементу словника по ключу з підстановкою
# дефолтного значення, якщо ключ в словнику не знайдений
# при використанні методу pop елемент зі словнику видаляється
tmp = d4.pop(None, "Такого ключа немає у словнику")
print(tmp)
print(d4) # значення -100, так як ключа test в словнику немає

10
{'a': [1, 3, 4, 5], 'b': (2, 3), 4: {5: {7: 8}}, (1, 3): 7, 7.8: [], True: ((5, ()), 5)}


In [ ]:
tmp = d4.pop('b', 2)
print('pop "b" = ' + str(tmp))
d4 # Елемент з ключем b видалений зі словника

pop "b" = (2, 3)


{(1, 3): 7, 4: {5: {7: 8}}, 7.8: [], True: ((5, ()), 5), 'a': [1, 3, 4, 5]}

In [ ]:
# Приклад вибірки значення по ключу з використанням методу get
tmp = d3.get('aa', "Такого ключа немає у словнику")
tmp

'Такого ключа немає у словнику'

In [ ]:
# Приклад вибірки значення по ключу з використанням методу get і значенням по замовчуванню
tmp = d4.get('b', 'nothing')
print('get "b" = ' + str(tmp))
print('d4 = ' + str(d4))

get "b" = nothing
d4 = {'a': [1, 3, 4, 5], 4: {5: {7: 8}}, (1, 3): 7, 7.8: [], True: ((5, ()), 5)}


In [ ]:
# Приклад вибірки всіх включів та значень
print('d4 keys = ' + str(d4.keys()))
print('d4 values = ' + str(d4.values()))

d4 keys = dict_keys(['a', 4, (1, 3), 7.8, True])
d4 values = dict_values([[1, 3, 4, 5], {5: {7: 8}}, 7, [], ((5, ()), 5)])


In [ ]:
d4.items()

dict_items([('a', [1, 3, 4, 5]), (4, {5: {7: 8}}), ((1, 3), 7), (7.8, []), (True, ((5, ()), 5))])

In [ ]:
# Приклад проходження по елементам в словнику через цикл for
for k, v in d4.items():
    print('{}-{}'.format(k, str(v)))

a-[1, 3, 4, 5]
4-{5: {7: 8}}
(1, 3)-7
7.8-[]
True-((5, ()), 5)


In [ ]:
list(d4.items())

[('a', [1, 3, 4, 5]),
 (4, {5: {7: 8}}),
 ((1, 3), 7),
 (7.8, []),
 (True, ((5, ()), 5))]

In [ ]:
# Приклад видалення елементу зі словника з використанням команди del
del d4[None]
d4

KeyError: ignored

In [ ]:
del df['type']

df

age  (87, 89)
0   20      True
1   20     False
2   20      True

In [ ]:
# Приклад помилки звернення по ключу
val = d1.get('val')
if val is None:
    print('here')

try:
    print(d1['val'])
except Exception as e:
    print('Error on get invalid key: ' + str(type(e)))

here
Error on get invalid key: <class 'KeyError'>


## set

Структура даних, яка дає можливість зберігати та працювати з невпорядкованим, унікальним набором елементів.

Набільш корисний функціонал - це виконання операцій union, intersection, difference, symmetric difference.

Офіційна документація - https://docs.python.org/3/library/stdtypes.html#set

In [ ]:
# Приклади оголошення set

s1 = {0, 5, 3, -1, -3, 0}
s2 = set()
s3 = {}
s4 = {10, 23, 54, -100, 287, -39, 0}
type(s3)
print('s1 = ' + str(s1))
print('s2 = ' + str(s2))
print('s3 = ' + str(s3))
print('s4 = ' + str(s4))

s1 = {0, 3, 5, -3, -1}
s2 = set()
s3 = {}
s4 = {0, 10, 54, 23, -39, -100, 287}


In [ ]:
np.array(list(set(np.array([1,2,23,4,5,2,1,1,4,67]))))

array([ 1,  2, 67,  4,  5, 23])

### Використання операцій над `set` через оператори

In [ ]:
print('s1 = ' + str(s1))
print('s4 = ' + str(s4))
s1 | s4  # union

s1 = {0, 3, 5, -3, -1}
s4 = {0, 10, 54, 23, -39, -100, 287}


{-100, -39, -3, -1, 0, 3, 5, 10, 23, 54, 287}

In [ ]:
print('s1 = ' + str(s1))
print('s4 = ' + str(s4))
s1 & s4  # intersection

s1 = {0, 3, 5, -3, -1}
s4 = {0, 10, 54, 23, -39, -100, 287}


{0}

In [ ]:
print('s1 = ' + str(s1))
print('s4 = ' + str(s4))
s1 - s4  # difference

s1 = {0, 3, 5, -3, -1}
s4 = {0, 10, 54, 23, -39, -100, 287}


{-3, -1, 3, 5}

In [ ]:
print('s1 = ' + str(s1))
print('s4 = ' + str(s4))
s1 ^ s4  # symmetric difference

s1 = {0, 3, 5, -3, -1}
s4 = {0, 10, 54, 23, -39, -100, 287}


{-100, -39, -3, -1, 3, 5, 10, 23, 54, 287}

### Використання операцій над `set` через вбудовані методи

In [ ]:
print('s1 = ' + str(s1))
print('s4 = ' + str(s4))
s1.union(s4)  # unio

s1 = {0, 3, 5, -3, -1}
s4 = {0, 10, 54, 23, -39, -100, 287}


{-100, -39, -3, -1, 0, 3, 5, 10, 23, 54, 287}

In [ ]:
print('s1 = ' + str(s1))
print('s4 = ' + str(s4))
s1.intersection(s4)  # intersection

s1 = {0, 3, 5, -3, -1}
s4 = {0, 10, 54, 23, -39, -100, 287}


{0}

In [ ]:
print('s1 = ' + str(s1))
print('s4 = ' + str(s4))
s1.difference(s4)  # difference

s1 = {0, 3, 5, -3, -1}
s4 = {0, 10, 54, 23, -39, -100, 287}


{-3, -1, 3, 5}

In [ ]:
print('s1 = ' + str(s1))
print('s4 = ' + str(s4))
s1.symmetric_difference(s4)  # symmetric difference

s1 = {0, 3, 5, -3, -1}
s4 = {0, 10, 54, 23, -39, -100, 287}


{-100, -39, -3, -1, 3, 5, 10, 23, 54, 287}

# Оператори управління потоком

## Конструкції умов: if, elif, else

Конструкції умов, які ще називають `if-then`, дають можливість виконувати окремі блоки кода, в залежності від певної Boolean умови.

Також існує тернарний оператор `x1 if b1 else x2`, який зазвичай використовується при ініцілазації змінних.

In [ ]:
print("10 > 50") if result else print('10 < 50')

10 > 50


In [ ]:
# Приклад використання if
result = 10 > 50

if result:
    print('10 > 50')
else:
    print('10 < 50')

# Приклад використання if-elif-else
a = 10
b = 50
if a > b:
    print('a > b')
elif a == b:
    print('a == b')
else:
    print("a ? b = ???")

l1 = [1, 2, 3]
l2 = [1, 2, 3]
l3 = l2

print(l2 is l3)

10 < 50
a ? b = ???
True


In [ ]:
# Приклад використання тернарного оператора
a = 10
b = 50
c = a if a > b else b
print('C = ' + str(c))

def func(a=None):
    aa = a if a is not None else 10

C = 50


In [ ]:
?np.array

Docstring:
array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)

Create an array.

Parameters
----------
object : array_like
    An array, any object exposing the array interface, an object whose
    __array__ method returns an array, or any (nested) sequence.
dtype : data-type, optional
    The desired data-type for the array.  If not given, then the type will
    be determined as the minimum type required to hold the objects in the
    sequence.  This argument can only be used to 'upcast' the array.  For
    downcasting, use the .astype(t) method.
copy : bool, optional
    If true (default), then the object is copied.  Otherwise, a copy will
    only be made if __array__ returns a copy, if obj is a nested sequence,
    or if a copy is needed to satisfy any of the other requirements
    (`dtype`, `order`, etc.).
order : {'K', 'A', 'C', 'F'}, optional
    Specify the memory layout of the array. If object is not an array, the
    newly created array will be in C order (

## Цикли: for, while

В Python цикли представлені `for` та `while`.

Цикли можна робити вкладеними, але це може негативно вплинути на швидкість роботи програми (особливо з надзвичайно великими масивами даних), читаємість коду.

Для роботи з циклами використовуються команди:
- `continue`: пропустити і перейти до наступної ітерації
- `break`: перервати виконання циклу

In [ ]:
# Приклад створення списку з 10 перших чисел
tmp = []
for i in range(21, 30, 1): 
    u = i+8
    tmp.append(u**2)
tmp

[841, 900, 961, 1024, 1089, 1156, 1225, 1296, 1369]

In [ ]:
# Приклад використання while
a = 10
b = 50

while a < b:
    print(a)
    a += 1
a

10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49


50

In [ ]:
tmp.extend([4, 88, 13, 99])

In [ ]:
# Приклад використання continue
# якщо значення елементу списку 4 або 7, то їх обробка не проводиться,
# але при цьому виконання циклу не завершується.
res = [[], []]
for val in tmp:
    if val in [4, 7]: # val >= 4 and val <= 7; 4 <= val <= 7
        continue
        #break
    if not bool(val % 2):  # приклад роботи з bool на основі int: якщо остача 0, то False, будь-яке інше значення - True
        res[0].append(val)
    else:
        res[1].append(val)
    
res

[[900, 1024, 1156, 1296], [841, 961, 1089, 1225, 1369]]

In [ ]:
# Приклад використання break
# якщо значення елементу списку більше 5, то цикл завершується і
# подальша обробака наступних елементів не виконується
res = [[], []]
for val in tmp:
    if val > 5:
        break
    if not bool(val % 2):
        res[0].append(val)
    else:
        res[1].append(val)
    
res

[[], []]

# Практичні завдання

## Завдання 1

Створити список з 10 елементів типу `int` від 1 до 10.

Знайти:
- суму всіх чисел
- добуток всіх чисел
- добуток тільки парних чисел
- сформувати новий список, кожний елемент якого це квадрат числа кожного елементу з вихідного списку

Результати роботи записувати в змінну `result` типу `dict`, де ключ - це номер завдання, а значення - результат

In [ ]:
in_list = list(range(1, 11))
result = dict()

# task 1
tmp = 0
for val in in_list:
    tmp += val

result[1] = tmp
result

{1: 55}

In [ ]:
# task 2
tmp = 1
for val in in_list:
    tmp *= val

result[2] = tmp
result

{1: 55, 2: 3628800}

In [ ]:
# task 3
tmp = 1
for val in in_list:
    tmp *= val if not val % 2 else 1

result[3] = tmp

In [ ]:
# task 4
tmp = []
i = 0
while True:
    val = in_list[i]
    tmp.append(val ** 2)
    
    i += 1
    if i >= len(in_list):
        break

result[4] = tmp
result

{1: 55, 2: 3628800, 3: 3840, 4: [1, 4, 9, 16, 25, 36, 49, 64, 81, 100]}

## Завдання 2
Створити список з 20 елементів типу `int` від 1 до 20.

Знайти:
- розбити список на два списки: парні та непарні числа; результата записати до словника з двома ключами під парні і непарні числа;
- кожне парне число піднести до степені, де степінь - це кожне непарне число; результат записати до словника, де ключ це рядок "a ** b", а значення - це результат піднесення до степені;
- розділити список на два, однакових за довжиною; по кожному списку створити новий, в якому всі двозначні числа розділені на цифри, наприклад, 13 - це 1 і 3;
- на основі отриманих списків з попереднього кроку, створити два set, над якими провести операції union, intersection, difference, symmetric_difference, а результати записати до словника, де ключ - це тип операції, а значення - отриманий результат.

In [ ]:
import copy
in_list = list(range(1, 21))

# task 1
key_1 = 'x % 2 == 0'
key_2 = 'x % 2 != 0'
result_1 = {
    key_1: [],
    key_2: []
}

for val in in_list:
    if val % 2:
        result_key = key_2
    else:
        result_key = key_1
    result_1[result_key].append(val)
result_1

{'x % 2 == 0': [2, 4, 6, 8, 10, 12, 14, 16, 18, 20],
 'x % 2 != 0': [1, 3, 5, 7, 9, 11, 13, 15, 17, 19]}

In [ ]:
# task 2
list_1 = copy.deepcopy(result_1[key_1])
list_2 = copy.deepcopy(result_1[key_2])

result_2 = dict()
i = 0
j = 0

while True:
    a = list_1[i]
    b = list_2[j]
    result_key = '{} ** {}'.format(a, b)
    
    result_2[result_key] = a ** b
    
    i += 1
    j += 1
    if i >= len(list_1) or j >= len(list_2):
        break

result_2

{'2 ** 1': 2,
 '4 ** 3': 64,
 '6 ** 5': 7776,
 '8 ** 7': 2097152,
 '10 ** 9': 1000000000,
 '12 ** 11': 743008370688,
 '14 ** 13': 793714773254144,
 '16 ** 15': 1152921504606846976,
 '18 ** 17': 2185911559738696531968,
 '20 ** 19': 5242880000000000000000000}

In [ ]:
# task 3
list_1 = in_list[:len(in_list) // 2]
list_2 = in_list[len(in_list) // 2:]

key_1 = 'list_1'
key_2 = 'list_2'
key_set = {key_1, key_2}

tmp_list = {
    key_1: list_1,
    key_2: list_2
}
result_3 = dict(((key_1, []), (key_2, [])))

for key in key_set:
    tmp_result = result_3[key]
    
    for val in tmp_list[key]:
        tmp_result.extend(list(str(val)))

result_3

{'list_1': ['1', '2', '3', '4', '5', '6', '7', '8', '9', '1', '0'],
 'list_2': ['1',
  '1',
  '1',
  '2',
  '1',
  '3',
  '1',
  '4',
  '1',
  '5',
  '1',
  '6',
  '1',
  '7',
  '1',
  '8',
  '1',
  '9',
  '2',
  '0']}

In [ ]:
# task 4

set_1 = set(result_3[key_1])
set_2 = set(result_3[key_2])

result_4 = {
    'union': set_1.union(set_2),
    'intersection': set_1.intersection(set_2),
    'difference': set_1.difference(set_2),
    'symmetric_difference': set_1.symmetric_difference(set_2) 
}

result_4

{'union': {'0', '1', '2', '3', '4', '5', '6', '7', '8', '9'},
 'intersection': {'0', '1', '2', '3', '4', '5', '6', '7', '8', '9'},
 'difference': set(),
 'symmetric_difference': set()}

In [ ]:
x = input()
g = []
if int(x) == 0:
    print("")
else:
    for i in range(int(x)+1):
        for j in range(i):
            g.append(i)
    for h in g[0:int(x)]:
        print(h, end = " ")
#print(g)

 4


1 2 2 3 

In [ ]:
# put your python code here

x = input()
y = input()

z = []

for i, value in enumerate(x):
    if(value == y):
        z.append(i)

if len(z) == 0:
    print("Отсутствует")
else:
    for j in z:
        print(j, end = " ")

 5
 5


0 

In [ ]:
for i in str(input()).split(" "):
    print(int(i))

 5


5


In [ ]:
import tensorflow

2+2